### ISSUE TITLE
Infinite height increase

### ISSUE THREAD

**Issue by ChambreNoire** [wellyshen/react-cool-dimensions#289]
# Bug Report

In scenarios where the observed div should take up all available space (height and width at 100%), I find that the height reported by react-cool-dimensions increases infinitely...

## StackblitzLink

https://stackblitz.com/edit/cool-dims-height

## Expected Behavior

The orange box should not resize independently of the window being resized

**Comment by wellyshen** [comment]
@ChambreNoire It's because the children of the `ResponsiveWrapper` causes extra `5px` when it's rendered. So every time you trigger the `canvas.update`, the height of the children is accumulated infinitely. You can solve this problem by setting the height of the `ResponsiveWrapper` to `99%`. It's more like a style issue but not the library.

**Comment by ChambreNoire** [comment]
Yeah that's the conclusion I came to eventually. Not too sure where the extra 5px are coming from in the context of the svg element but in my case it's just a matter of making the svg element's height and width = 100%.
Thanks!
