### ISSUE TITLE
Custom resize handlers

### ISSUE THREAD

**Issue by sp-daniel-sanchez** [wellyshen/react-cool-dimensions#36]
# Feature Request

## Describe the Feature

First, good job with the library! It works flawlessly!
I would like to use it in a style guide i'm building, and would be nice to be able to first, define the places where the resize handler will be available (right, top, left, bottom, top-right..)
And on top of that, be able to pass a custom component to handle the resize (instead of the circle you currently have in the bottom-right corner).
Do you think is possible to do? 
If it is and you are busy, I can try to work on that and do a PR.

## Additional Information

I'm currently using this one https://github.com/bokuweb/re-resizable, which gives you a handleComponent attribute to override the handlers.

**Comment by wellyshen** [comment]
@sp-daniel-sanchez Thank you for giving it a try. For your idea, I think it's possible but the purpose of this library is to provide the **general information of dimensions** to help developer building their components instead of handling the components for developers. If you think it's useful I suggest that you can leverage it to achieve your idea.

**Comment by sp-daniel-sanchez** [comment]
Oops!! You're right, totally misunderstood the purpose of the hook :P
Thanks for your answer!!

**Comment by wellyshen** [comment]
@sp-daniel-sanchez I'm thinking the possible of provide the coordinate axis of the corners and center of an element. But I don't know how many user need this feature. How do you think about it?
